@startuml Tracking
title LArSoft Tracking

skinparam componentStyle rectangle
skinparam stereotype {
  CBackgroundColor<<Producer>> #DFF5E1
  CBackgroundColor<<Filter>>   #FFEBD6
  CBackgroundColor<<Analyzer>> #E7E9FF
}
skinparam rectangle {
  BorderColor #888
  RoundCorner 8
}

legend left
  <<Producer>>  makes data products
  (dp)          data product type
endlegend

package "Event (art::Event)" {
  () "recob::PFParticle" as PF
  () "recob::Track/recob::Shower" as TrSh
  () "anab::Calorimetry" as Calo
}

component "Track/Shower" <<Producer>> as TrackShower
component "Calorimetry"  <<Producer>> as CaloProd

PF         -up-> TrackShower : reads
TrackShower -down-> TrSh : produces

TrSh     -up-> CaloProd : reads
CaloProd -down-> Calo : produces

@enduml

